/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "intstore.h"

bool_t
xdr_list (XDR *xdrs, list *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->list_val, (u_int *) &objp->list_len, 8,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
