/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intstore.h"
#include <stdlib.h>

static int *vector;
static int length = 0;
static int capacity = 0;

void *
append_1_svc(list *argp, struct svc_req *rqstp)
{
	printf("Appending %i elements\n", argp->list_len);
	static char * result;

	if (length + argp->list_len > capacity) {
		capacity = length + argp->list_len;
		vector = (int *) realloc(vector, capacity * sizeof(int));
	}

	for (int i = 0; i < argp->list_len; i++) {
		vector[length + i] = argp->list_val[i];
	}

	length += argp->list_len;

	return (void *) &result;
}

int *
query_1_svc(int *argp, struct svc_req *rqstp)
{
	if (*argp < 0 || *argp >= length) {
		printf("Index out of bounds: list has size %i but index is %i\n", length, *argp);
		return (int *) NULL;
	}

	return &vector[*argp];
}

void *
remove_1_svc(int *argp, struct svc_req *rqstp)
{
	if (*argp < 0 || *argp >= length) {
		printf("Index out of bounds: list has size %i but index is %i\n", length, *argp);
		return (void *) NULL;
	}

	for (int i = *argp; i < length - 1; i++) {
		vector[i] = vector[i + 1];
	}

	length--;
}
